# Generated by Django 4.1.3 on 2022-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_result_sentences_photo_result_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="category",
            field=models.CharField(
                choices=[("0", "スニーカー判別"), ("1", "説明文生成")], default="0", max_length=1
            ),
        ),
    ]
